# This namespace contains a demo server that presents a server certificate
# issued by row-major.net/service-dns, and a client that presents a
# client certificate issued by row-major.net/spiffe.

apiVersion: v1
kind: Namespace
metadata:
  name: service-dns-spiffe-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: service-dns-spiffe-client
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ghcr.io/ahmedtd/meshtool:latest
        command:
        - /meshtool
        - demo-server
        - --listen=0.0.0.0:443
        - --server-creds=/run/tls-config/service-dns-cred-bundle.pem
        - --enable-spiffe-client-support=true
        - --spiffe-trust-bundle=/run/tls-config/spiffe-trust-bundle.pem
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tls-config
          mountPath: /run/tls-config
      volumes:
      - name: tls-config
        projected:
          sources:
          - podCertificate:
              signerName: row-major.net/service-dns
              keyType: ECDSAP256
              credentialBundlePath: service-dns-cred-bundle.pem
          - clusterTrustBundle:
              signerName: row-major.net/spiffe
              labelSelector:
                matchLabels:
                  "spiffe.row-major.net/canarying": "live"
                  "spiffe.row-major.net/trust-domain": "cluster.local"
              path: spiffe-trust-bundle.pem
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: service-dns-spiffe-client
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
  selector: {
    app: server,
  }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: service-dns-spiffe-client
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Always
      containers:
      - name: client
        image: ghcr.io/ahmedtd/meshtool:latest
        command:
        - /meshtool
        - https-client
        - --fetch-url=https://server.service-dns-spiffe-client.svc/spiffe-echo
        - --server-trust-bundle=/run/tls-config/service-dns-trust-bundle.pem
        - --client-cred-bundle=/run/tls-config/spiffe-cred-bundle.pem
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tls-config
          mountPath: /run/tls-config
      volumes:
      - name: tls-config
        projected:
          sources:
          - clusterTrustBundle:
              signerName: row-major.net/service-dns
              labelSelector:
                matchLabels:
                  "service-dns.row-major.net/canarying": "live"
              path: service-dns-trust-bundle.pem
          - podCertificate:
              signerName: row-major.net/spiffe
              keyType: ED25519
              credentialBundlePath: spiffe-cred-bundle.pem