apiVersion: v1
kind: Namespace
metadata:
  name: mesh-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshtool-signer
rules:
# The service signer needs to be able to read services and pods.
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - podcertificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - clustertrustbundles
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - certificates.k8s.io
  resources:
  - podcertificaterequests/status
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - row-major.net/*
  verbs:
  - sign
  - attest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshtool-is-a-meshtool-signer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshtool-signer
subjects:
- kind: ServiceAccount
  namespace: mesh-controller
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-controller
  namespace: mesh-controller
  labels:
    app: mesh-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-controller
  template:
    metadata:
      labels:
        app: mesh-controller
    spec:
      containers:
      - name: controller
        image: ahmedtd111/meshtool:latest
        command:
        - /meshtool
        - controller
        - --in-cluster=true
        - --enable-service-dns-signer=true
        - --service-dns-ca-pool=/run/ca-state/service-dns-pool.json
        - --enable-spiffe-signer=true
        - --spiffe-trust-domain=cluster.local
        - --spiffe-ca-pool=/run/ca-state/spiffe-pool.json
        volumeMounts: [
          {
            name: "ca-state",
            mountPath: "/run/ca-state",
          }
        ]
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: "ca-state"
        projected:
          sources:
          - secret:
              name: "service-dns-ca-pool"
              items: 
              - key: "pool"
                path: "service-dns-pool.json"
          - secret:
              name: "spiffe-ca-pool"
              items:
              - key: "pool"
                path: "spiffe-pool.json"
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
