apiVersion: v1
kind: Namespace
metadata:
  name: mesh-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshtool-signer
rules:
# The service signer needs to be able to read services and pods.
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - podcertificaterequests
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - clustertrustbundles
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - certificates.k8s.io
  resources:
  - podcertificaterequests/status
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - row-major.net/*
  verbs:
  - sign
  - attest
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshtool-is-a-meshtool-signer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshtool-signer
subjects:
- kind: ServiceAccount
  namespace: mesh-controller
  name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mesh-controller
  name: meshtool-controller
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meshtool-is-a-meshtool-controller
  namespace: mesh-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: meshtool-controller
subjects:
- kind: ServiceAccount
  namespace: mesh-controller
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-controller
  namespace: mesh-controller
  labels:
    app: mesh-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-controller
  template:
    metadata:
      labels:
        app: mesh-controller
    spec:
      containers:
      - name: controller
        image: ghcr.io/ahmedtd/meshtool:0.0.2@sha256:19fdc24fe2eff6896f03f61885da535a66b20bf60b721a50ff44b9278f87a52e
        command:
        - /meshtool
        - controller
        - --in-cluster=true
        - --sharding-pod-namespace=$(POD_NAMESPACE)
        - --sharding-pod-name=$(POD_NAME)
        - --sharding-pod-uid=$(POD_UID)
        - --sharding-application-name=mesh-controller
        - --enable-service-dns-signer=true
        - --service-dns-ca-pool=/run/ca-state/service-dns-pool.json
        - --enable-spiffe-signer=true
        - --spiffe-trust-domain=cluster.local
        - --spiffe-ca-pool=/run/ca-state/spiffe-pool.json
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: "ca-state"
          mountPath: "/run/ca-state"
        - name: "acme-client"
          mountPath: "/run/acme-client"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: "ca-state"
        projected:
          sources:
          - secret:
              name: "service-dns-ca-pool"
              items: 
              - key: "pool"
                path: "service-dns-pool.json"
          - secret:
              name: "spiffe-ca-pool"
              items:
              - key: "pool"
                path: "spiffe-pool.json"
      - name: "acme-client"
        projected:
          sources:
          - secret:
              name: "acme-client-key"
              items:
              - key: "client-private-key.pkcs8"
                path: "client-private-key.pkcs8"
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
