/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PKCS10RequestParameterSpecApplyConfiguration represents a declarative configuration of the PKCS10RequestParameterSpec type for use
// with apply.
//
// PKCS10RequestParameterSpec allows the pod author to minimally customize the
// stub PKCS#10 certificate signing request that Kubelet will generate using the
// subject private key.
//
// See the ACME Identifier Types registry [1] for PKCS#10 fields that
// ACME-compatible CAs *may* support.
//
// In total, up to 100 SANs may be requested.
//
// [1] https://www.iana.org/assignments/acme/acme.xhtml#acme-identifier-types
type PKCS10RequestParameterSpecApplyConfiguration struct {
	// DNS Subject Alternate Names that will be included in the request.
	//
	// Each entry will be validated as a DNS name (maximum length 253, all
	// ASCII characters).
	DNS []string `json:"dns,omitempty"`
	// IP Address Subject Alternate Names that will be included in the request.
	//
	// Entries must be either IPv4 addresses in dotted-decimal form ("192.0.2.1"),
	// or IPv6 addresses ("2001:db8::68").
	IPAddresses []string `json:"ipAdresses,omitempty"`
}

// PKCS10RequestParameterSpecApplyConfiguration constructs a declarative configuration of the PKCS10RequestParameterSpec type for use with
// apply.
func PKCS10RequestParameterSpec() *PKCS10RequestParameterSpecApplyConfiguration {
	return &PKCS10RequestParameterSpecApplyConfiguration{}
}

// WithDNS adds the given value to the DNS field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DNS field.
func (b *PKCS10RequestParameterSpecApplyConfiguration) WithDNS(values ...string) *PKCS10RequestParameterSpecApplyConfiguration {
	for i := range values {
		b.DNS = append(b.DNS, values[i])
	}
	return b
}

// WithIPAddresses adds the given value to the IPAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPAddresses field.
func (b *PKCS10RequestParameterSpecApplyConfiguration) WithIPAddresses(values ...string) *PKCS10RequestParameterSpecApplyConfiguration {
	for i := range values {
		b.IPAddresses = append(b.IPAddresses, values[i])
	}
	return b
}
